"""
Layout and geometry constants for the EREBUS presentation layer.
"""


HEADER_HEIGHT = 116
HEADER_PADX = 28
HEADER_PADY = (18, 8)

MAIN_AREA_PADX = 28
MAIN_AREA_PADY = (6, 28)

SIDEBAR_WIDTH = 178
SIDEBAR_BUTTON_HEIGHT = 56

CARD_CORNER_RADIUS = 14
CARD_PADX = 10
CARD_PADY = (0, 20)

POPUP_WIDTH = 680
POPUP_HEIGHT = 132
POPUP_TARGET_X = 34
POPUP_Y = 8
POPUP_SLIDE_EXTRA_OFFSET = 20
POPUP_CLOSE_BUTTON_WIDTH = 96
POPUP_CLOSE_BUTTON_HEIGHT = 38