"""
Timing, polling and animation constants for the EREBUS presentation layer.
"""


CONSOLE_POLL_INTERVAL_MS = 100

TOOLTIP_DELAY_MS = 450
TOOLTIP_WRAP_LENGTH = 390

POPUP_ANIMATION_INTERVAL_MS = 12
POPUP_ANIMATION_FACTOR = 0.22
POPUP_ANIMATION_MIN_STEP = 2

WINDOWS_NOTIFICATION_SOUND = "SystemHand"

LOADING_OVERLAY_START_DELAY_MS = 120
LOADING_OVERLAY_HIDE_DELAY_MS = 350