"""
Console page for the EREBUS graphical interface.

This page displays stdout and stderr messages generated by the GUI and by the
EREBUS execution engine.
"""

import customtkinter as ctk

import presentation.constants as C


class ConsolePage(ctk.CTkFrame):
    """
    Page that displays the runtime console output.
    """

    def __init__(self, parent, fonts):
        """
        Initializes the console page.

        Args:
            parent: Parent widget.
            fonts: Application font catalog.
        """
        super().__init__(parent, corner_radius=0)

        self.fonts = fonts
        self.console_textbox = None
        self.clear_button = None

        self._build()

    def _build(self):
        """
        Builds the console page layout.
        """
        self.grid_columnconfigure(0, weight=1)
        self.grid_rowconfigure(0, weight=0)
        self.grid_rowconfigure(1, weight=1)

        header = ctk.CTkFrame(self, fg_color="transparent")
        header.grid(row=0, column=0, sticky="ew", padx=14, pady=(14, 10))
        header.grid_columnconfigure(0, weight=1)
        header.grid_columnconfigure(1, weight=0)

        title = ctk.CTkLabel(
            header,
            text=C.CONSOLE_TITLE,
            font=self.fonts["section"],
        )
        title.grid(row=0, column=0, sticky="w")

        self.clear_button = ctk.CTkButton(
            header,
            text="Clear console",
            width=180,
            height=42,
            corner_radius=6,
            font=self.fonts["button"],
            command=self.clear,
        )
        self.clear_button.grid(row=0, column=1, sticky="e", padx=(12, 0))

        self.console_textbox = ctk.CTkTextbox(
            self,
            font=self.fonts["console"],
            wrap="none",
            corner_radius=10,
        )
        self.console_textbox.grid(
            row=1,
            column=0,
            sticky="nsew",
            padx=14,
            pady=(0, 14),
        )
        self.console_textbox.configure(state="disabled")

        self._style_textbox()
        self.append(C.CONSOLE_READY_TEXT)

    def append(self, text, is_error=False):
        """
        Appends text to the console textbox.

        Args:
            text: Text to append.
            is_error: Whether the text comes from stderr.
        """
        if not self.console_textbox:
            return

        self.console_textbox.configure(state="normal")
        self.console_textbox.insert("end", text)
        self.console_textbox.see("end")
        self.console_textbox.configure(state="disabled")

    def clear(self):
        """
        Clears the console textbox.
        """
        if not self.console_textbox:
            return

        self.console_textbox.configure(state="normal")
        self.console_textbox.delete("1.0", "end")
        self.console_textbox.configure(state="disabled")

    def apply_theme(self, palette):
        """
        Applies the active theme to the console page.

        Args:
            palette: Active theme palette.
        """
        self.configure(fg_color=palette["panel"])

        if self.console_textbox:
            self.console_textbox.configure(
                fg_color=palette["console_bg"],
                text_color=palette["text"],
                border_color=palette["soft"],
                border_width=1,
            )
            self._style_textbox()

        if self.clear_button:
            self.clear_button.configure(
                fg_color=palette["secondary"],
                hover_color=palette["secondary_hover"],
                text_color=palette["text"],
                border_width=0,
            )

    def _style_textbox(self):
        """
        Applies extra spacing and internal padding to the console textbox.
        """
        if not self.console_textbox:
            return

        try:
            self.console_textbox._textbox.configure(
                padx=14,
                pady=12,
                spacing1=2,
                spacing2=1,
                spacing3=5,
            )
        except AttributeError:
            pass