from .base_repository import BaseRepository


class MetricsRepository(BaseRepository):
    """
    Repository responsible for storing and retrieving execution metrics,
    including both module-level and derived analytics metrics.
    """

    def insert_module_metrics(self, execution_id: str, module_name: str, metrics: dict) -> None:
        """
        Inserts or updates metrics generated by a module.
        """
        for metric_name, value in metrics.items():

            # Ensure value is numeric (defensive)
            if not isinstance(value, (int, float)):
                continue

            self._execute(
                """
                INSERT OR REPLACE INTO execution_metrics
                (execution_id, module_name, metric_name, metric_value)
                VALUES (?, ?, ?, ?)
                """,
                (
                    execution_id,
                    module_name,
                    metric_name,
                    value,
                ),
            )

    # ------------------------------------------------
    # Derived analytics metrics
    # ------------------------------------------------

    def insert_derived_metrics(self, execution_id: str) -> None:
        """
        Computes and inserts derived analytics metrics based on stored data.
        """

        # Remove previous analytics metrics
        self._execute(
            """
            DELETE FROM execution_metrics
            WHERE execution_id = ?
            AND module_name = 'analytics'
            """,
            (execution_id,),
        )

        # -------- Emails --------

        self._execute(
            """
            INSERT INTO execution_metrics
            (execution_id, module_name, metric_name, metric_value)

            SELECT ?, 'analytics', 'emails_total', COUNT(*)
            FROM email_results
            WHERE execution_id = ?
            """,
            (execution_id, execution_id),
        )

        self._execute(
            """
            INSERT INTO execution_metrics
            (execution_id, module_name, metric_name, metric_value)

            SELECT ?, 'analytics', 'emails_detected_by_scraping', COUNT(*)
            FROM email_results
            WHERE execution_id = ?
              AND technique IN ('scraping_dom', 'scraping_json')
            """,
            (execution_id, execution_id),
        )

        self._execute(
            """
            INSERT INTO execution_metrics
            (execution_id, module_name, metric_name, metric_value)

            SELECT ?, 'analytics', 'emails_detected_without_scraping', COUNT(*)
            FROM email_results
            WHERE execution_id = ?
              AND technique NOT IN ('scraping_dom', 'scraping_json')
            """,
            (execution_id, execution_id),
        )

        # -------- Credentials --------

        self._execute(
            """
            INSERT INTO execution_metrics
            (execution_id, module_name, metric_name, metric_value)

            SELECT ?, 'analytics', 'creds_total', COUNT(*)
            FROM credential_results
            WHERE execution_id = ?
            """,
            (execution_id, execution_id),
        )

    # ------------------------------------------------
    # Retrieval
    # ------------------------------------------------

    def get_execution_metrics(self, execution_id: str) -> dict:
        """
        Retrieves all metrics grouped by module.
        """
        rows = self._fetchall(
            """
            SELECT module_name, metric_name, metric_value
            FROM execution_metrics
            WHERE execution_id = ?
            """,
            (execution_id,),
        )

        result = {}

        for module, metric, value in rows:
            result.setdefault(module, {})[metric] = value

        return result